[platformio]
default_envs = disco_f746ng
src_dir = src
include_dir = include

[env:disco_f746ng]
platform = ststm32
board = disco_f746ng
framework = stm32cube
build_flags =
  -std=c11
  -Wall
  -Wextra
  -Werror=return-type
  -DTG4132_HW_REV_A=1
monitor_speed = 115200
